version: '3.8'

services:
  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    volumes:
      - /root/src/src/:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  mariadb-master:
    container_name: mariadb_master
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - 'db_master_data:/var/lib/mysql'
      - './first-host.cnf:/etc/mysql/conf.d/mysql_extra.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testovoe_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password2
    networks:
      - app-network
   
  mariadb-slave:
    container_name: mariadb_slave
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - 'db_slave_data:/var/lib/mysql'
      - './second-host.cnf:/etc/mysql/conf.d/mysql_extra.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testovoe_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password2
    networks:
      - app-network
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: testovoe
    container_name: testovoe
    volumes:
      - './src/:/var/www'
      - '.env:/var/www/.env'
    networks:
      - app-network

networks:
  app-network:
     driver: bridge

volumes:
 db_master_data:
    name: db_master_data
    driver: local
 db_slave_data:
    name: db_slave_data
    driver: local
